version: '3.8'

services:
  mysql:
    image: vulns-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  django:
    build: .
    command: ["./wait-for-it.sh", "mysql:3306", "-t", "45", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./config/nginx/html:/usr/share/nginx/html
      - ./static:/static
      - ./media:/media
    depends_on:
      - django

volumes:
  mysql_data:
